spring.application.name=maricloud-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/maricloud
spring.datasource.username=maricloud
spring.datasource.password=${MARI_CLOUD_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

minio.url=${MINIO_URL}
minio.username=${MINIO_ROOT_USER}
minio.password=${MINIO_ROOT_PASSWORD}

maricloud.storage.limit-bytes=10737418240
